### PR TITLE
Security updates to jquery

### PR DESCRIPTION
**Pull request by LindsayHill**
Bumped jquery version in package.json and updated npm-shrinkwrap.json.

YOLO merge?

### CODE REVIEW

**Comment by Kami** [comment]
Probably need to rebuild the asset bundles?

**Comment by LindsayHill** [comment]
Ah yes, that's right - because of the way this one is served, probably does need that rebuild

**Comment by LindsayHill** [comment]
I did `npm run build` locally, and pushed the updated docs/assets/bundle.js file. That cover it?

**Comment by Kami** [comment]
Yeah, that should do it :+1:

**Comment by LindsayHill** [comment]
I'm not 100% certain this is all OK, because npm updates are always like this to me https://media.giphy.com/media/3o6Mbtdd7dhvbvugg0/giphy.gif

Will merge, do some further tests, revert if necessary

**Comment by LindsayHill** [comment]
Heh https://github.com/StackStorm-Exchange/web/issues/18

**Comment by Kami** [comment]
Yeah, perhaps we should set up circle ci :)

**Comment by LindsayHill** [comment]
Was looking OK when I tested yesterday. Wonder if I was still getting some older cached content

**Comment by Kami** [comment]
Likely, I needed to purge CloudFlare cache for my revert changes to take an affect...

**Pull request merged**
