### PR TITLE
Make logo and header text link to the homepage

### PR DESCRIPTION
**Pull request by Kami**
The title says it all.

I haven't been able to test it locally yet since `npm run build` fails - https://gist.github.com/Kami/f2e1f2837983338cc778b1ec27b75bbf.

### CODE REVIEW

**Comment by emedvedev** [comment]
LGTM. I'll merge this, won't hurt. I did the logo link, too. 😛 

As I said on Slack, I'm going to push a large PR by EOD, with the help popups and fixed builder/loaders, so better not to do anything significant here today.

**Comment by Kami** [comment]
Sounds good.

I just want to make sure it doesn't break the style or smth.

**Comment by Kami** [comment]
I was also thinking about maybe linking logo to stackstorm website and just the header text to the exchange homepage.

WDYT?

**Comment by emedvedev** [comment]
Could get a little weird, as it's a completely separate site: if we introduce other pages at some point, people will click on the logo assuming it takes them to the main page, not the stackstorm website :) There's StackStorm links in the footer, but we could move them to the header and make more prominent somehow, probably.

**Pull request merged**
